version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka_broker
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  client_site:
    build:
      context: ./client_site
      dockerfile: Dockerfile
    container_name: client_site
    environment:
      KAFKA_BROKER_URL: kafka:9092
    depends_on:
      - kafka

  product_service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    container_name: product_service
    environment:
      KAFKA_BROKER_URL: kafka:9092
    depends_on:
      - kafka